version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - storage:/var/lib/mysql

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
    volumes:
        - $PWD/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
        - ./:/var/www/
    depends_on:
        - mysql
        - meilisearch

  php-fpm:
    build:
      target: php-fpm
    restart: unless-stopped
    environment:
      - INIT_INSTALL=1
    volumes:
      - ./:/var/www/:rw,cached
    depends_on:
      - mysql
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
        - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
    volumes:
        - meilisearch:/meili_data
    ports:
        - 7700:7700
    depends_on:
        - mysql

volumes:
  storage:
  meilisearch:
